### ISSUE TITLE
POST json

### ISSUE THREAD

**Issue by ecco15** [Wampirue/phalcon-rest#6]
when i request get respon with url : http://192.168.0.126/phalcon-rest-master/users, i get result : [{"id":"1","login":"robet"},{"id":"2","login":"andi"}]...
how to POST JSOn or add new data in users with users or other? i newbe in phalcon, i hope you can help me sir. thank before

**Comment by Wampirue** [comment]
If I understand correct you would like to POST data to server. Do you tried to use Postman? It is free plugin that allows you to send other request than GET.

https://chrome.google.com/webstore/detail/postman/fhbjgbiflinjbdggehcddcbncdddomop

**Comment by ecco15** [comment]
yes i will POST data to server,postman its free but i like develop with phalcon rest api..can i post data with your basic resp api?

**Comment by Wampirue** [comment]
You can post TO api, not by the api. Api only recives request ans serves response.

**Comment by ecco15** [comment]
when i try request data with postman:
request: PUT http://rest.encrypted.pl/users/1
request JSON:
{
    "login": "admin_new",
    "password": "5baa61e4c9b93f3f0682250b6cf8331b7ee68fd8",
    "pubkey": "123456",
    "old_password": "5baa61e4c9b93f3f0682250b6cf8331b7ee68fd8"
}

i get result : 
{
  "status": "ERROR",
  "data": "Access is not authorized"
}

How to fix the issues? thank before sir

**Comment by Wampirue** [comment]
You are posting to wrong url. Post to: `http://192.168.0.126/phalcon-rest-master/users` without any ID.
