### ISSUE TITLE
PUT issues

### ISSUE THREAD

**Issue by ecco15** [Wampirue/phalcon-rest#7]
when i try : 
curl -i -X PUT http://localhost/phalcon-rest-master/users/2

I get result:
Status : 401 Unauthorized
{
  "status": "ERROR",
  "data": "Access is not authorized"
}

what i should do for this issue?

**Comment by Wampirue** [comment]
You cand PUT to ```http://localhost/phalcon-rest-master/users/2``` you should PUT to ```http://localhost/phalcon-rest-master/users```
