### ISSUE TITLE
Requests with data doesn't work

### ISSUE THREAD

**Issue by J05HI** [Wampirue/phalcon-rest#8]
@Wampirue 
How to fire requests with data?
I'm using Phalcon 3.1.2, maby that's the problem.

I'm getting this:

![postman](https://user-images.githubusercontent.com/16399787/28155779-715a9cc8-67b0-11e7-8ff2-8faa88e05e55.PNG)

**Comment by Wampirue** [comment]
You need to send input as JSON not as POST array

**Comment by J05HI** [comment]
Thx :)
